[package]
name = "ai-kinda-rust"
version = "0.1.0"
authors = ["ThatCreeper <creeper_host@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
